
#include "Fit/Fitter.h"
#include "Fit/BinData.h"
#include "Fit/Chi2FCN.h"
#include "TH1.h"
#include "TList.h"
#include "Math/WrappedMultiTF1.h"
#include "HFitInterface.h"
#include "TCanvas.h"
#include "TStyle.h"

void test1()
{
  TH1D * h1 = new TH1D("h1","histo generated by random number", 100, 0, 100);
  TF1 * f1 = new TF1("f1","gaus",0, 100);
  f1->SetParameters(1, 30, 5);
  h1->FillRandom("f1",10000);

  TH1D * hic = (TH1D*)h1->Clone();
//  hic->Draw();

  ROOT::Fit::DataOptions opt;
//  opt.fIntegral = true;
  ROOT::Fit::DataRange range(10, 50);
  ROOT::Fit::BinData   data(opt, range);
  ROOT::Fit::FillData(data, hic);

  TF1 * fit = new TF1("fit", "gaus");
  ROOT::Math::WrappedMultiTF1 fitfunc(*fit,fit->GetNdim());
  ROOT::Fit::Chi2Function chi2(data, fitfunc);


  Double_t par[3] = {1, 1, 1};
  ROOT::Fit::Fitter fitter;
  fitter.SetFunction(fitfunc, false);
  fitter.Config().SetParamsSettings(3, par);

  fitter.Config().SetMinimizer("Minuit", "Migrad");

  fitter.FitFCN(3, chi2, 0, data.Size(), true);
/*
//  ROOT::Fit::FitResult result = fitter.Result();
//   result.Print(std::cout);  */


}
