reverses = $(1) $(2)
exec:
		@echo $(subst ee,EE,feet on the street)
		@echo $(sort LIFE IS BEAUTIFUL)
		@echo $(word 2, LIFE IS BEAUTIFUL)
		@echo $(call reverses,a,b)
		@echo $(origin reverses)
		@echo $(shell echo *.c)
